from .image import Image
from .about import About
from .embed import Embed
from .instagram_embed import Instagram_Embed
from .spotify_embed import Spotify_Embed
from .youtube_embed import Youtube_Embed
from .widget import WidgetBase
from .twitter_embed import Twitter_Embed
from .applemusic_Embed import Applemusic_Embed
from .linkedin_Embed import Linkedin_Embed